# Generated by Django 2.1.4 on 2019-01-03 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jub_list',
            new_name='Job_list',
        ),
    ]
