# Generated by Django 2.1.4 on 2019-01-03 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20190104_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_list',
            name='logo',
        ),
    ]
