# Generated by Django 2.1.4 on 2019-01-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_remove_job_list_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_list',
            name='description',
            field=models.TextField(default='說明職務內容'),
        ),
    ]
