# Generated by Django 2.1.4 on 2019-01-04 01:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_job_list_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_list',
            name='logo',
            field=models.ImageField(default='說明職務內容', upload_to='photos'),
        ),
        migrations.AddField(
            model_name='job_list',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
