# Generated by Django 2.1.4 on 2019-01-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(default='SOME STRING', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
