# Generated by Django 2.1.4 on 2019-01-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0011_auto_20190105_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='enabled',
            new_name='company',
        ),
    ]
