# Generated by Django 2.1.4 on 2019-01-05 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0013_auto_20190105_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='student',
            new_name='company',
        ),
    ]
