# Generated by Django 2.1.4 on 2019-01-05 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0015_auto_20190105_2035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
