# Generated by Django 2.1.4 on 2019-01-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0016_delete_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_list',
            name='company_email',
            field=models.EmailField(default='請輸入廠商email', max_length=254),
        ),
    ]
