# Generated by Django 2.1.4 on 2019-01-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0017_job_list_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_list',
            name='bonus',
            field=models.CharField(default='請輸入福利', max_length=200),
        ),
        migrations.AddField(
            model_name='job_list',
            name='pay',
            field=models.CharField(default='請輸入薪水', max_length=200),
        ),
    ]
