# Generated by Django 2.1.4 on 2019-01-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0018_auto_20190106_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_list',
            name='education',
            field=models.CharField(default='學歷需求', max_length=20),
        ),
    ]
