# Generated by Django 2.1.4 on 2019-01-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0019_job_list_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_list',
            name='about_company',
            field=models.CharField(default='公司描述', max_length=20),
        ),
    ]
